[bumpver]
current_version = "1.0"
version_pattern = "YYYY.BUILD[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"setup.py" = [
    "{version}",
    "{pep440_version}",
]
"README.md" = [
    "{version}",
    "{pep440_version}",
]
"bumpver.toml" = [
    'current_version = "{version}"',
]

[project]
name = "Niimpy"
version = "1.0"
authors = [
  { name="Talayeh Aledavood", email="talayeh.aledavood@aalto.fi" },
]
description = "Python module for analysis of behavioral data"
readme = "README.md"
requires-python = ">=3.5"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/digitraceslab/niimpy"
"Bug Tracker" = "https://github.com/digitraceslab/niimpy/issues"